---
PATH_hg38: "/groups/wyattgrp/users/jbacon/reference/hg38/hs38DH.fa"
# PATH_hg38: "../references/hg38.fa"
# PATH_hg38: "/groups/wyattgrp/users/amunzur/hla_pipeline/resources/hg38/hg38_with_hla.fa"
# PATH_bed: "/groups/wyattgrp/reference/target/medexome/MedExome_hg38_capture_targets.bed"
PATH_bed: "resources/hla_panel/target_regions.bed"
PATH_gcwig: "resources/genome_gc50.wig.gz"
DIR_fastq: "results/data/fq"
DIR_fastqc_raw: "results/reports/fastqc_raw"
DIR_fastqc_processed: "results/reports/fastqc_processed"
DIR_bams: "results/data/bam"
DIR_metrics: "results/metrics"
DIR_results: "results"
DIR_resources: "resources"
DIR_temp: "results/temp"
